version: '3.8'

services:
  banco_clima_timescale:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb_g8
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=trabalho_nosql
    ports:
      - "5432:5432"
    volumes:
      - timescale_dados:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  timescale_dados: